# Generated by Django 2.1.5 on 2019-01-16 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 6, 37, 3, 115949, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
